development:
  clients:
    default:
      database: admin
      hosts:
        - localhost:27017
      options:
  options:

production:
  clients:
    default:
      uri: mongodb+srv://doadmin:5pu7a3608j21kwCK@ramirez-a7eae1d8.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=ramirez
      options:
        ssl: true
    
test:
  clients:
    default:
      database: ramirez_test
      hosts:
        - mongodb+srv://doadmin:5pu7a3608j21kwCK@ramirez-a7eae1d8.mongo.ondigitalocean.com/admin?tls=true&authSource=admin&replicaSet=ramirez
      options:
  options:
